// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shuwjedbpimcfzjftylf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNodXdqZWRicGltY2Z6amZ0eWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDU0NzksImV4cCI6MjA1ODQyMTQ3OX0.4sZOXmvOdtWpbfrcWZzMPVjN17tsBuy_p38Qlv454Gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);