
import { ReproductoraDespatch, EngordeDespatch, ExcelPreviewData } from '@/lib/types';

/**
 * Generates comprehensive preview data for an Excel file
 * This would be replaced with actual Excel parsing in a real application
 */
export const generatePreviewData = (file: File): ExcelPreviewData => {
  // En una implementación real, aquí procesaríamos el archivo Excel completo
  // Por ahora, usamos datos de muestra ampliados para simular la carga completa
  
  // Sample data - REPRODUCTORA sheet (mostrando todos los registros)
  const reproData: ReproductoraDespatch[] = [
    {
      ubicacion: 'GARAGOA',
      granja: 'BARSAL 1',
      lote: 'E30',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'FASE 2 COBB',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MARTES 25',
      cantidad: 275,
      ton: 11,
      orden: '224230',
      conductor: 'ANDRES SABOGAL',
      placa: 'WHK 426',
      cedula: '1,056,580,224',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'SAN ESTEBAN 2',
      lote: 'E52',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'LEVANTE',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 375,
      ton: 15,
      orden: '224231',
      conductor: 'FERNANDO VANEGAS',
      placa: 'SRD 194',
      cedula: '1048847155',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'SAN MIGUEL',
      lote: 'E17',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'FASE 3 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 350,
      ton: 14,
      orden: '224234',
      conductor: 'MARTIN CHAVEZ',
      placa: 'WPK 570',
      cedula: '73335175',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'ZONA CENTRAL BAJA',
      lote: 'E18',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 2 COBB',
      medicacion: 'P/CROMICINA-FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 350,
      ton: 14,
      orden: '1114222',
      conductor: 'HENRY ESGUERRA',
      placa: 'XXB191',
      cedula: '74,335,566',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '7:00 p. m.',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'ZONA CENTRAL BAJA',
      lote: 'E18',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS COBB',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 25,
      ton: 1,
      orden: '1114222',
      conductor: 'HENRY ESGUERRA',
      placa: 'XXB191',
      cedula: '74,335,566',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    // Registros adicionales para completar la carga (simulando carga completa)
    {
      ubicacion: 'GARAGOA',
      granja: 'LAS PALMAS',
      lote: 'E22',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'FASE 1 ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'JUEVES 27',
      cantidad: 300,
      ton: 12,
      orden: '224240',
      conductor: 'ROBERTO SUÁREZ',
      placa: 'TGH 781',
      cedula: '79245186',
      remisionPlanta: 'JUEVES 27',
      observaciones: '',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'BUENOS AIRES',
      lote: 'E33',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'INICIACIÓN ROSS',
      medicacion: 'BIOMODULADOR-HEPATOPROTECTOR',
      dia: 'JUEVES 27',
      cantidad: 225,
      ton: 9,
      orden: '1114260',
      conductor: 'JAIME TORRES',
      placa: 'KLM 432',
      cedula: '80761234',
      remisionPlanta: 'JUEVES 27',
      observaciones: '',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'EL MOLINO',
      lote: 'E40',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'FASE 2 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR',
      dia: 'VIERNES 28',
      cantidad: 400,
      ton: 16,
      orden: '224250',
      conductor: 'CARLOS FORERO',
      placa: 'WDF 327',
      cedula: '1057863421',
      remisionPlanta: 'VIERNES 28',
      observaciones: 'Entrega prioritaria',
    },
  ];
  
  // Sample data - ENGORDE sheet (mostrando todos los registros)
  const engordeData: EngordeDespatch[] = [
    {
      granja: 'NARANJAL (NARANJ)',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 200,
      toneladas: 8,
      confirmar: '',
      ubicacion: 'SAN FRANCISCO',
      tecnico: 'CARLOS CASTIBLANCO',
      orden: '224248',
      conductor: 'OSWALDO RODRIGUEZ',
      placa: 'WNX 547',
      cedula: '79137559',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MIREYAS',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 125,
      toneladas: 5,
      confirmar: '',
      ubicacion: 'LA MESA',
      tecnico: 'CARLOS CENEN',
      orden: '224249',
      conductor: 'HUGO VEGA',
      placa: 'WPT 526',
      cedula: '80311610',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'VILLA LORENA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 150,
      toneladas: 6,
      confirmar: '',
      ubicacion: 'FUSAGASUGA',
      tecnico: 'SONIA',
      orden: '224226',
      conductor: 'NELSON GARAVITO',
      placa: 'USB 969',
      cedula: '1003558901',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'GUADUAS',
      dia: 'MARTES 25',
      planta: 'ITALCOL-FUNZA',
      nomAlimento: 'FASE 1 ROSS',
      cantidad: 137,
      toneladas: 5.48,
      confirmar: '',
      ubicacion: 'PORVENIR (UVE)',
      tecnico: 'TECNICO1',
      orden: '1114252',
      conductor: 'JAROL DURAN',
      placa: 'GIT 950',
      cedula: '1073511288',
      remision: 'MIERCOLES 25',
    },
    {
      granja: 'LA MESA',
      dia: 'MARTES 25',
      planta: 'ITALCOL-FUNZA',
      nomAlimento: 'FASE 2 ROSS',
      cantidad: 100,
      toneladas: 4,
      confirmar: '',
      ubicacion: 'LA MARIA 1',
      tecnico: 'TECNICO2',
      orden: '1114273',
      conductor: 'GERMAN CALDERON',
      placa: 'NOX 203',
      cedula: '79063368',
      remision: 'MIERCOLES 25',
    },
    // Registros adicionales para completar la carga (simulando carga completa)
    {
      granja: 'POTRERITOS',
      dia: 'JUEVES 27',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 175,
      toneladas: 7,
      confirmar: '',
      ubicacion: 'CACHIPAY',
      tecnico: 'SAMUEL ORTIZ',
      orden: '224260',
      conductor: 'JAVIER MENDEZ',
      placa: 'PLO 612',
      cedula: '71582963',
      remision: 'JUEVES 27',
    },
    {
      granja: 'EL RECUERDO',
      dia: 'VIERNES 28',
      planta: 'ITALCOL-FUNZA',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 225,
      toneladas: 9,
      confirmar: '',
      ubicacion: 'MANZANARES',
      tecnico: 'DIANA RUBIO',
      orden: '1114290',
      conductor: 'GUILLERMO PARRA',
      placa: 'TDF 421',
      cedula: '1023587456',
      remision: 'VIERNES 28',
    },
    {
      granja: 'EL PARAISO',
      dia: 'VIERNES 28',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'FINALIZADOR PREMIUM',
      cantidad: 180,
      toneladas: 7.2,
      confirmar: '',
      ubicacion: 'LA VEGA',
      tecnico: 'CAMILO TORRES',
      orden: '224275',
      conductor: 'AUGUSTO REYES',
      placa: 'KJH 523',
      cedula: '80432789',
      remision: 'VIERNES 28',
    },
  ];
  
  return {
    reproductora: reproData,
    engorde: engordeData,
    totalRecords: reproData.length + engordeData.length
  };
};
