
import { ReproductoraDespatch, EngordeDespatch, ExcelPreviewData } from '@/lib/types';

/**
 * Generates comprehensive preview data for an Excel file
 * This would be replaced with actual Excel parsing in a real application
 */
export const generatePreviewData = (file: File): ExcelPreviewData => {
  // En una implementación real, aquí procesaríamos el archivo Excel completo
  // Simulamos la lectura completa de las hojas mostradas en las imágenes
  
  // Sample data - REPRODUCTORA sheet (todos los registros de la imagen)
  const reproData: ReproductoraDespatch[] = [
    {
      ubicacion: 'GARAGOA',
      granja: 'BARSAL 1',
      lote: 'E30',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'FASE 2 COBB',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MARTES 25',
      cantidad: 275,
      ton: 11,
      orden: '224230',
      conductor: 'ANDRES SABOGAL',
      placa: 'WHK 426',
      cedula: '1,056,580,224',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'SAN ESTEBAN 2',
      lote: '652',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'LEVANTE',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 375,
      ton: 15,
      orden: '224231',
      conductor: 'FERNANDO VANEGAS',
      placa: 'SRD 194',
      cedula: '1048847155',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'SAN MIGUEL',
      lote: '617',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'FASE 3 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 350,
      ton: 14,
      orden: '224234',
      conductor: 'MARTIN CHAVEZ',
      placa: 'WPK 570',
      cedula: '74335175',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'ZONA CENTRAL BAJA',
      lote: '618',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 2 COBB',
      medicacion: 'P/CROMICINA-FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 350,
      ton: 14,
      orden: '1114222',
      conductor: 'HENRY ESGUERRA',
      placa: 'XXB191',
      cedula: '74,335,566',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '7:00 p. m.',
    },
    {
      ubicacion: 'GARAGOA',
      granja: 'ZONA CENTRAL BAJA',
      lote: '618',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS COBB',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 25,
      ton: 1,
      orden: '1114222',
      conductor: 'HENRY ESGUERRA',
      placa: 'XXB191',
      cedula: '74,335,546',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'GUADUAS',
      granja: 'PORVENIR (UVE1)',
      lote: '646',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 1 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 350,
      ton: 14,
      orden: '1114225',
      conductor: 'AUGUSTO DURAN',
      placa: 'UQA 241',
      cedula: '1073246673',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '8:00 a. m.',
    },
    {
      ubicacion: 'GUADUAS',
      granja: 'PORVENIR (UVE3)',
      lote: '648',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 1 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MARTES 25',
      cantidad: 137,
      ton: 5.48,
      orden: '1114252',
      conductor: 'JAROL DURAN',
      placa: 'GIT 950',
      cedula: '1073511288',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '6:00 p. m.',
    },
    {
      ubicacion: 'GUADUAS',
      granja: 'PORVENIR (UVE3)',
      lote: '648',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 1 ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'MARTES 25',
      cantidad: 38,
      ton: 1.52,
      orden: '1114252',
      conductor: 'JAROL DURAN',
      placa: 'GIT 950',
      cedula: '1073511288',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'BRISAS 1',
      lote: '649',
      planta: 'ALBATEQ-ALBATEQ',
      tipoAlimento: 'CRECIMIENTO',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 300,
      ton: 12,
      orden: '224236',
      conductor: 'LUIS TORRES',
      placa: 'SNB 197',
      cedula: '3,073,195',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'MAPORITA',
      lote: '639',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 2 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 300,
      ton: 12,
      orden: '1114214',
      conductor: 'DANIEL VARGAS',
      placa: 'ASG 748',
      cedula: '1071550525',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '6:00 a. m.',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'ISABELLA',
      lote: '640',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 2 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MARTES 25',
      cantidad: 300,
      ton: 12,
      orden: '1114254',
      conductor: 'CARLOS MARTINEZ',
      placa: 'CLC 335',
      cedula: '7334164',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '10:00 a. m.',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'MIREYA',
      lote: '642',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 1 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MARTES 25',
      cantidad: 150,
      ton: 6,
      orden: '1114257',
      conductor: 'MAIRON PARRA',
      placa: 'SLE 817',
      cedula: '1023992770',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '9:00 a. m.',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'CEIBA',
      lote: '645',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 1 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 250,
      ton: 10,
      orden: '1114264',
      conductor: 'FELIPE CALDERON',
      placa: 'XKF 301',
      cedula: '1072432117',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '3:00 p. m.',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'CEIBA',
      lote: '645',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 50,
      ton: 2,
      orden: '1114264',
      conductor: 'FELIPE CALDERON',
      placa: 'XKF 301',
      cedula: '1072432117',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'LA MARIA 1',
      lote: '633',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 1 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MARTES 25',
      cantidad: 100,
      ton: 4,
      orden: '1114273',
      conductor: 'GERMAN CALDERON',
      placa: 'NOX 203',
      cedula: '79063368',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '2:00 p. m.',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'LA MARIA 1',
      lote: '633',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'MARTES 25',
      cantidad: 25,
      ton: 1,
      orden: '1114273',
      conductor: 'GERMAN CALDERON',
      placa: 'NOX 203',
      cedula: '79063368',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    // Seguimos agregando los demás registros que se ven en la imagen
    {
      ubicacion: 'LA MESA',
      granja: 'LA MARIA 2',
      lote: '634',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 2 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MARTES 25',
      cantidad: 100,
      ton: 4,
      orden: '1114273',
      conductor: 'GERMAN CALDERON',
      placa: 'NOX 203',
      cedula: '79063368',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'LA MARIA 2',
      lote: '634',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'MARTES 25',
      cantidad: 12,
      ton: 0.48,
      orden: '1114273',
      conductor: 'GERMAN CALDERON',
      placa: 'NOX 203',
      cedula: '79063368',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'LA MARIA 3',
      lote: '637',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 1 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MARTES 25',
      cantidad: 50,
      ton: 2,
      orden: '1114273',
      conductor: 'GERMAN CALDERON',
      placa: 'NOX 203',
      cedula: '79063368',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'LA MARIA 3',
      lote: '637',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'MARTES 25',
      cantidad: 13,
      ton: 0.52,
      orden: '1114273',
      conductor: 'GERMAN CALDERON',
      placa: 'NOX 203',
      cedula: '79063368',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'VILLA ROSITA',
      lote: '623',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 3 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 250,
      ton: 10,
      orden: '1114275',
      conductor: 'JAIRO GUZMAN',
      placa: 'SVE 757',
      cedula: '2960975',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '11:00 a. m.',
    },
    {
      ubicacion: 'LA MESA',
      granja: 'VILLA ROSITA',
      lote: '623',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 50,
      ton: 2,
      orden: '1114275',
      conductor: 'JAIRO GUZMAN',
      placa: 'SVE 757',
      cedula: '2960975',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'GUACATA 2',
      lote: '620',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 3 COBB',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 50,
      ton: 2,
      orden: '1114278',
      conductor: 'NERFE MAYORGA',
      placa: 'SVA 603',
      cedula: '3,152,251',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '7:00 a. m.',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'GUACATA 3',
      lote: '621',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 3 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 25,
      ton: 1,
      orden: '1114278',
      conductor: 'NERFE MAYORGA',
      placa: 'SVA 603',
      cedula: '3,152,251',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'GUACATA 4',
      lote: '622',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'FASE 3 ROSS',
      medicacion: 'FINBIOX-HEPATOSTAR-OVOCLEAN',
      dia: 'MIERCOLES 26',
      cantidad: 150,
      ton: 6,
      orden: '1114278',
      conductor: 'NERFE MAYORGA',
      placa: 'SVA 603',
      cedula: '3,152,251',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'GUACATA 3',
      lote: '621',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 25,
      ton: 1,
      orden: '1114278',
      conductor: 'NERFE MAYORGA',
      placa: 'SVA 603',
      cedula: '3,152,251',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    },
    {
      ubicacion: 'FUSAGASUGA',
      granja: 'GUACATA 4',
      lote: '622',
      planta: 'ITALCOL-FUNZA',
      tipoAlimento: 'MACHOS ROSS',
      medicacion: 'SIN MEDICAR',
      dia: 'MIERCOLES 26',
      cantidad: 50,
      ton: 2,
      orden: '1114278',
      conductor: 'NERFE MAYORGA',
      placa: 'SVA 603',
      cedula: '3,152,251',
      remisionPlanta: 'MIERCOLES 25',
      observaciones: '',
    }
  ];
  
  // Sample data - ENGORDE sheet (todos los registros de la imagen)
  const engordeData: EngordeDespatch[] = [
    {
      granja: 'NARANJAL (NARANJ)',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 200,
      toneladas: 8,
      confirmar: '',
      ubicacion: 'SAN FRANCISCO',
      tecnico: 'CARLOS CASTIBLANCO',
      orden: '224248',
      conductor: 'OSWALDO RODRIGUEZ',
      placa: 'WNX 547',
      cedula: '73127559',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MIREYAS',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 125,
      toneladas: 5,
      confirmar: '',
      ubicacion: 'LA MESA',
      tecnico: 'CARLOS CENEN',
      orden: '224249',
      conductor: 'HUGO VEGA',
      placa: 'WPT 526',
      cedula: '80311610',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MIREYAS',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 125,
      toneladas: 5,
      confirmar: '',
      ubicacion: 'LA MESA',
      tecnico: 'CARLOS CENEN',
      orden: '224249',
      conductor: 'HUGO VEGA',
      placa: 'WPT 526',
      cedula: '80311610',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SAMUEL',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACIÓN CORRIENTE',
      cantidad: 250,
      toneladas: 10,
      confirmar: '',
      ubicacion: 'LA MESA',
      tecnico: 'FELIPE MARTINEZ',
      orden: '224251',
      conductor: 'SAUL PATARROYO',
      placa: 'WPT 522',
      cedula: '79063511',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'VILLA LORENA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 150,
      toneladas: 6,
      confirmar: '',
      ubicacion: 'FUSAGASUGA',
      tecnico: 'SONIA',
      orden: '224226',
      conductor: 'NELSON GARAVITO',
      placa: 'USB 969',
      cedula: '1003558901',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'VILLA LORENA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 150,
      toneladas: 6,
      confirmar: '',
      ubicacion: 'FUSAGASUGA',
      tecnico: 'SONIA',
      orden: '224226',
      conductor: 'NELSON GARAVITO',
      placa: 'USB 969',
      cedula: '1003558901',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'VICTORIA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACION CORRIENTE',
      cantidad: 200,
      toneladas: 8,
      confirmar: '',
      ubicacion: 'SILVANIA',
      tecnico: 'SONIA',
      orden: '224252',
      conductor: 'ALEJANDRO MARTINEZ',
      placa: 'SRD 193',
      cedula: '13,223,941',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'VICTORIA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACION CORRIENTE',
      cantidad: 200,
      toneladas: 8,
      confirmar: '',
      ubicacion: 'SILVANIA',
      tecnico: 'SONIA',
      orden: '224253',
      conductor: 'JOSE PATIVA',
      placa: 'ONE 555',
      cedula: '4062085',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SANTA ANA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 150,
      toneladas: 6,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'CARLOS NIÑO',
      orden: '224254',
      conductor: 'NELSON GARAVITO',
      placa: 'USB 969',
      cedula: '1003558901',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SANTA ANA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 150,
      toneladas: 6,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'CARLOS NIÑO',
      orden: '224254',
      conductor: 'NELSON GARAVITO',
      placa: 'USB 969',
      cedula: '1003558901',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SAN JUAN',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 300,
      toneladas: 12,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'CARLOS NIÑO',
      orden: '224255',
      conductor: 'JAIME ROJAS',
      placa: 'WUA 443',
      cedula: '10715882',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'DELICIAS',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 300,
      toneladas: 12,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'CARLOS NIÑO',
      orden: '224256',
      conductor: 'WILSON VARGAS',
      placa: 'XKD 935',
      cedula: '3069552',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'DELICIAS',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 300,
      toneladas: 12,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'CARLOS NIÑO',
      orden: '224257',
      conductor: 'ALVARO SABOGAL',
      placa: 'SRD 568',
      cedula: '11383102',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'RINCON',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACION CORRIENTE',
      cantidad: 150,
      toneladas: 6,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'CARLOS NIÑO',
      orden: '224258',
      conductor: 'JUAN BORDA',
      placa: 'AJE 382',
      cedula: '1003614531',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'FLORESTA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACION CORRIENTE',
      cantidad: 100,
      toneladas: 4,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'CARLOS NIÑO',
      orden: '224259',
      conductor: 'JUAN BORDA',
      placa: 'AJE 382',
      cedula: '1003614531',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'FLORESTA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 50,
      toneladas: 2,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'CARLOS NIÑO',
      orden: '224259',
      conductor: 'JUAN BORDA',
      placa: 'AJE 382',
      cedula: '1003614531',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SELVA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'PREINICIADOR',
      cantidad: 200,
      toneladas: 8,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'YIMY SIERRA',
      orden: '224260',
      conductor: 'ROBINSON HERNANDEZ',
      placa: 'JTZ 488',
      cedula: '1073236035',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SELVA',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACION CORRIENTE',
      cantidad: 50,
      toneladas: 2,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'YIMY SIERRA',
      orden: '224260',
      conductor: 'ROBINSON HERNANDEZ',
      placa: 'JTZ 488',
      cedula: '1073236035',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MEXICO',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 300,
      toneladas: 12,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'YIMY SIERRA',
      orden: '224261',
      conductor: 'DAVI OLMOS',
      placa: 'BDA 360',
      cedula: '1070327602',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'ORATORIO',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 300,
      toneladas: 12,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'YIMY SIERRA',
      orden: '224262',
      conductor: 'ALEJANDRO MARTINEZ',
      placa: 'SRD 193',
      cedula: '13,223,941',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SAN ROQUE',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 300,
      toneladas: 12,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'YIMY SIERRA',
      orden: '224263',
      conductor: 'ERNESTO QUEVEDO',
      placa: 'SPB 454',
      cedula: '2,963,776',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SAN ROQUE',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 300,
      toneladas: 12,
      confirmar: '',
      ubicacion: 'ARBELAEZ',
      tecnico: 'YIMY SIERRA',
      orden: '224264',
      conductor: 'CLEMENTE CARVAJAL',
      placa: 'TND 676',
      cedula: '534875',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MANGUITOS 1',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'PREINICIADOR',
      cantidad: 250,
      toneladas: 10,
      confirmar: 'GL 32',
      ubicacion: 'ARBELAEZ',
      tecnico: 'HAROLDO',
      orden: '224265',
      conductor: 'ALEXANDER PARRADO',
      placa: 'TNB 901',
      cedula: '80242407',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MANGUITOS 1',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'PREINICIADOR',
      cantidad: 225,
      toneladas: 9,
      confirmar: 'GL 31',
      ubicacion: 'ARBELAEZ',
      tecnico: 'HAROLDO',
      orden: '224267',
      conductor: 'ALVARO LOPEZ',
      placa: 'IND 177',
      cedula: '2364702',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MANGUITOS 1',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACION CORRIENTE',
      cantidad: 25,
      toneladas: 1,
      confirmar: 'GL 31',
      ubicacion: 'ARBELAEZ',
      tecnico: 'HAROLDO',
      orden: '224267',
      conductor: 'ALVARO LOPEZ',
      placa: 'IND 177',
      cedula: '2364702',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MARBELLA 3',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'PREINICIADOR',
      cantidad: 200,
      toneladas: 8,
      confirmar: 'GL 29/30',
      ubicacion: 'ARBELAEZ',
      tecnico: 'HAROLDO',
      orden: '224268',
      conductor: 'OSCAR GOMEZ',
      placa: 'SNK 427',
      cedula: '11343390',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'MARBELLA 3',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACION CORRIENTE',
      cantidad: 50,
      toneladas: 2,
      confirmar: 'GL 29/30',
      ubicacion: 'ARBELAEZ',
      tecnico: 'HAROLDO',
      orden: '224268',
      conductor: 'OSCAR GOMEZ',
      placa: 'SNK 427',
      cedula: '11343390',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'POLLILANDIA (PT)',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'SOBREPIGMENTADO PELLETEADO',
      cantidad: 140,
      toneladas: 5.6,
      confirmar: '',
      ubicacion: 'SOMONDOCO',
      tecnico: 'FELIPE BARON',
      orden: '224270',
      conductor: 'MARIO VERGARA',
      placa: 'WZH 466',
      cedula: '4,130,397',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'POLLILANDIA (PT)',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 135,
      toneladas: 5.4,
      confirmar: '',
      ubicacion: 'SOMONDOCO',
      tecnico: 'FELIPE BARON',
      orden: '224270',
      conductor: 'MARIO VERGARA',
      placa: 'WZH 466',
      cedula: '4,130,397',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'RANCHOS',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 200,
      toneladas: 8,
      confirmar: '',
      ubicacion: 'GUATEQUE',
      tecnico: 'FELIPE BARON',
      orden: '224272',
      conductor: 'YEISON PINILLA',
      placa: 'OQF 427',
      cedula: '1049736323',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'RANCHOS',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 175,
      toneladas: 7,
      confirmar: '',
      ubicacion: 'GUATEQUE',
      tecnico: 'FELIPE BARON',
      orden: '224272',
      conductor: 'YEISON PINILLA',
      placa: 'OQF 427',
      cedula: '1049736323',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'RANCHOS',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PELLETEADO',
      cantidad: 350,
      toneladas: 14,
      confirmar: '',
      ubicacion: 'GUATEQUE',
      tecnico: 'FELIPE BARON',
      orden: '224273',
      conductor: 'FELIPE MARTINEZ',
      placa: 'SPB 855',
      cedula: '1053724743',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'EL RECUERDO (PT)',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE CORRIENTE',
      cantidad: 350,
      toneladas: 14,
      confirmar: '',
      ubicacion: 'SOMONDOCO',
      tecnico: 'FELIPE BARON',
      orden: '224276',
      conductor: 'OSCAR RODRIGUEZ',
      placa: 'LTA 352',
      cedula: '1068975818',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SAN FELIPE (PT)',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'INICIACION CORRIENTE',
      cantidad: 150,
      toneladas: 6,
      confirmar: '',
      ubicacion: 'SOMONDOCO',
      tecnico: 'FELIPE BARON',
      orden: '224277',
      conductor: 'IVAN FERNANDO',
      placa: 'SNL 014',
      cedula: '1049735432',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'SAN FELIPE (PT)',
      dia: 'MARTES 25',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PELLETEADO',
      cantidad: 200,
      toneladas: 8,
      confirmar: '',
      ubicacion: 'SOMONDOCO',
      tecnico: 'FELIPE BARON',
      orden: '224278',
      conductor: 'IVAN FERNANDO',
      placa: 'SNL 014',
      cedula: '1049735432',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'VILLANELLY 2',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 50,
      toneladas: 2,
      confirmar: '',
      ubicacion: 'IBAGUE',
      tecnico: 'JUANCHO GAMBOA',
      orden: '224280',
      conductor: 'NEYDER GABELLO',
      placa: 'SVE 930',
      cedula: '1072895527',
      remision: 'MIERCOLES 26',
    },
    {
      granja: 'VILLA GLORIA 1',
      dia: 'MIERCOLES 26',
      planta: 'ALBATEQ-ALBATEQ',
      nomAlimento: 'ENGORDE PIGMENTADO',
      cantidad: 175,
      toneladas: 7,
      confirmar: '',
      ubicacion: 'IBAGUE',
      tecnico: 'JUANCHO GAMBOA',
      orden: '224281',
      conductor: 'NEYDER GABELLO',
      placa: 'SVE 930',
      cedula: '1072895527',
      remision: 'MIERCOLES 26',
    }
  ];
  
  return {
    reproductora: reproData,
    engorde: engordeData,
    totalRecords: reproData.length + engordeData.length
  };
};
